apply plugin: 'com.android.application'

android {
    namespace 'com.ssnwt.playertest'
    compileSdkVersion 34
    defaultConfig {
        applicationId "com.ssnwt.androidapitest"
        minSdkVersion 26
        targetSdkVersion 31
        versionCode 1
        versionName "1.0"

        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'
}
